In [1]:
import cosmic.utils as cu
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
path = './MyDB_DachuanTian.csv'
df_raw = pd.read_csv(path)
df_raw.head()

,specobjid,survey,ra,dec,z_noqso,zErr_noqso,zwarning_noqso,class_noqso,z,zErr,zwarning,class,boss_target1,eboss_target0,eboss_target1,eboss_target2
0,4128819906056837120,boss,113.93314,37.277750,0.513258,0.000167,0,GALAXY,0.513258,0.000167,0,GALAXY,14,0,0,0
1,4128820180934744064,boss,114.00441,37.187478,0.020552,0.000118,5,GALAXY,0.020552,0.000118,5,GALAXY,0,0,0,0
2,4128820187310086144,boss,114.03501,37.339353,0.788482,0.000294,5,GALAXY,0.418801,0.000144,5,QSO,0,0,0,0
3,4128820455812651008,boss,114.14137,37.204149,0.510003,0.000190,0,GALAXY,0.510003,0.000190,0,GALAXY,14,0,0,0
4,4128821555324278784,boss,114.03681,37.074475,0.514531,0.000190,0,GALAXY,0.514531,0.000190,0,GALAXY,14,0,0,0

In [6]:
df_raw.survey.unique()

array(['boss', 'eboss', 'sdss', 'segue1', 'segue2'], dtype=object)

In [25]:
df = df_raw.copy()

idx = (df['survey'] == 'boss') | (df['survey'] == 'eboss')
mask_boss_eboss = (df['z_noqso'] > 0.) 
mask_boss_eboss &= (df['zErr_noqso'] > 0)
mask_boss_eboss &= (df['zwarning_noqso'] == 0)
mask_boss_eboss &= (df['class_noqso'] == 'GALAXY')
df_boss_eboss = df.loc[idx & mask_boss_eboss]

mask_others = (df['z'] > 0.) 
mask_others &= (df['zErr'] > 0)
mask_others &= (df['zwarning'] == 0)
mask_others &= (df['class'] == 'GALAXY')
df_others = df.loc[~idx & mask_others]

df_save = pd.concat([df_boss_eboss, df_others], axis=0)
print(df_save.shape)

(2864989, 16)

In [28]:
idx = (df_save['survey'] == 'boss') | (df_save['survey'] == 'eboss')
df_save[idx].head()

,specobjid,survey,ra,dec,z_noqso,zErr_noqso,zwarning_noqso,class_noqso,z,zErr,zwarning,class,boss_target1,eboss_target0,eboss_target1,eboss_target2
0,4128819906056837120,boss,113.93314,37.277750,0.513258,0.000167,0,GALAXY,0.513258,0.000167,0,GALAXY,14,0,0,0
3,4128820455812651008,boss,114.14137,37.204149,0.510003,0.000190,0,GALAXY,0.510003,0.000190,0,GALAXY,14,0,0,0
4,4128821555324278784,boss,114.03681,37.074475,0.514531,0.000190,0,GALAXY,0.514531,0.000190,0,GALAXY,14,0,0,0
5,4128823204591720448,boss,114.01484,37.283752,0.482296,0.000161,0,GALAXY,0.482296,0.000161,0,GALAXY,14,0,0,0
6,4128823210967062528,boss,114.04621,36.955689,0.515358,0.000163,0,GALAXY,0.515358,0.000163,0,GALAXY,6,0,0,0

In [19]:
df_save.specobjid.duplicated().sum()

np.int64(0)

In [20]:
df_save.columns

Index(['specobjid', 'survey', 'ra', 'dec', 'z_noqso', 'zErr_noqso',
       'zwarning_noqso', 'class_noqso', 'z', 'zErr', 'zwarning', 'class',
       'boss_target1', 'eboss_target0', 'eboss_target1', 'eboss_target2'],
      dtype='object')

In [29]:
cols_save = ['specobjid', 'ra', 'dec', 'z', 'zErr']
df_save = df_save[cols_save]
df_save.columns = ['SDSS_' + col for col in df_save.columns]
df_save.head()

        SDSS_specobjid    SDSS_ra   SDSS_dec    SDSS_z  SDSS_zErr
0  4128819906056837120  113.93314  37.277750  0.513258   0.000167
3  4128820455812651008  114.14137  37.204149  0.510003   0.000190
4  4128821555324278784  114.03681  37.074475  0.514531   0.000190
5  4128823204591720448  114.01484  37.283752  0.482296   0.000161
6  4128823210967062528  114.04621  36.955689  0.515358   0.000163

In [30]:
output_path = './sdss_dr19.fits'
cu.savefile(df_save, output_path)

# SDSS DR19 STAR

In [4]:
path = './SDSSDR19_STARQSO.csv'
df_raw = pd.read_csv(path)
df_raw.head()

,specObjID,bestObjID,ra,dec,class,subClass,z,zErr,zWarning
0,8908346135221131264,1237678880490258896,14.864501,-2.467043,QSO,BROADLINE,0.737914,0.000101,0
1,8908346410099038208,1237679435061788905,14.738038,-2.313158,QSO,BROADLINE,1.629690,0.001051,0
2,5116253377035261952,1237678906787758325,12.048423,10.120547,STAR,G4V (32923),-0.000733,0.000052,0
3,5116253651913168896,1237678906787758539,12.147548,10.107069,QSO,NaN,2.906836,0.000688,0
4,5116254201668982784,1237678906787823673,12.232475,10.116517,QSO,BROADLINE,2.560580,0.000559,0

In [6]:
df_starqso = df_raw[['ra','dec']]

output_path = './SDSSDR19_STARQSO_loc.fits'
cu.savefile(df_starqso, output_path)