In [1]:
import cosmic.utils as cu
import pandas as pd
import numpy as np
from astropy.io import fits
from astropy.table import Table

# LRG

In [2]:
path = './LRG_full_noveto.dat.fits'
with fits.open(path) as hdul:
    header = hdul[1].header
    data = hdul[1].data
    tab = Table(data)

In [4]:
tab.columns

<TableColumns names=('TARGETID','MWS_TARGET','SUBPRIORITY','PRIORITY_INIT','TARGET_STATE','TIMESTAMP','LOCATION','TILEID','TILELOCID','LASTNIGHT','Z','ZERR','ZWARN','CHI2','COEFF','NPIXELS','SPECTYPE','SUBTYPE','NCOEFF','DELTACHI2','FIBER','COADD_FIBERSTATUS','FIBERASSIGN_X','FIBERASSIGN_Y','PRIORITY','COADD_NUMEXP','COADD_EXPTIME','COADD_NUMNIGHT','MEAN_DELTA_X','RMS_DELTA_X','MEAN_DELTA_Y','RMS_DELTA_Y','MEAN_PSF_TO_FIBER_SPECFLUX','TSNR2_ELG_B','TSNR2_LYA_B','TSNR2_BGS_B','TSNR2_QSO_B','TSNR2_LRG_B','TSNR2_ELG_R','TSNR2_LYA_R','TSNR2_BGS_R','TSNR2_QSO_R','TSNR2_LRG_R','TSNR2_ELG_Z','TSNR2_LYA_Z','TSNR2_BGS_Z','TSNR2_QSO_Z','TSNR2_LRG_Z','TSNR2_ELG','TSNR2_LYA','TSNR2_BGS','TSNR2_QSO','TSNR2_LRG','ZWARN_MTL','Z_QN','Z_QN_CONF','IS_QSO_QN','PRIORITY_ASSIGNED','GOODPRI','GOODHARDLOC','LOCATION_ASSIGNED','TILELOCID_ASSIGNED','NTILE','TILES','TILELOCIDS','BRICKID','BRICKNAME','MORPHTYPE','RA','DEC','DCHISQ','EBV','FLUX_G','FLUX_R','FLUX_Z','FLUX_IVAR_G','FLUX_IVAR_R','FLUX_IVAR_Z','MW_TRANSMISSION_G','MW_TRANSMISSION_R','MW_TRANSMISSION_Z','NOBS_G','NOBS_R','NOBS_Z','PSFDEPTH_G','PSFDEPTH_R','PSFDEPTH_Z','GALDEPTH_G','GALDEPTH_R','GALDEPTH_Z','FLUX_W1','FLUX_W2','FLUX_IVAR_W1','FLUX_IVAR_W2','MW_TRANSMISSION_W1','MW_TRANSMISSION_W2','FIBERFLUX_G','FIBERFLUX_R','FIBERFLUX_Z','FIBERTOTFLUX_G','FIBERTOTFLUX_R','FIBERTOTFLUX_Z','WISEMASK_W1','WISEMASK_W2','MASKBITS','SHAPE_R','PHOTSYS','DESI_TARGET','BGS_TARGET','COMP_TILE','FRACZ_TILELOCID','lrg_mask','WEIGHT_ZFAIL','mod_success_rate')>

In [3]:
cols = ['TARGETID', 'RA', 'DEC', 'Z', 'ZERR', 'ZWARN',
        'SPECTYPE', 'DELTACHI2', 'MASKBITS', 'DESI_TARGET', 'BGS_TARGET',
        'PRIORITY', 'MORPHTYPE',
        'FLUX_G','FLUX_R','FLUX_Z', 'FLUX_W1','FLUX_W2',
        'FLUX_IVAR_G','FLUX_IVAR_R','FLUX_IVAR_Z','FLUX_IVAR_W1','FLUX_IVAR_W2']
df = tab[cols].to_pandas()

In [5]:
# clean
# ref: Zhou2024
mask = df['SPECTYPE'] == 'GALAXY'
mask &= df['ZWARN'] == 0
mask &= df['MASKBITS'] == 0
mask &= df['MORPHTYPE'] != 'PSF'
mask &= (df['DESI_TARGET'] & 2**0) != 0 # LRG
mask &= (df['FLUX_G']>0) & (df['FLUX_R']>0) & (df['FLUX_Z']>0) 
mask &= (df['FLUX_W1']>0) & (df['FLUX_W2']>0)
mask &= (df['FLUX_IVAR_G']>0) & (df['FLUX_IVAR_R']>0) & (df['FLUX_IVAR_Z']>0) 
mask &= (df['FLUX_IVAR_W1']>0) & (df['FLUX_IVAR_W2']>0)
mask &= df['DELTACHI2'] > 25

cols_save = ['TARGETID', 'RA', 'DEC', 'Z', 'ZERR',
            'DELTACHI2', 'DESI_TARGET', 'BGS_TARGET',
            'PRIORITY']

df_save = df[mask][cols_save]
print(df_save.shape)
df_save.head()

(2399821, 9)

,TARGETID,RA,DEC,Z,ZERR,DELTACHI2,DESI_TARGET,BGS_TARGET,PRIORITY
0,39627322696933879,21.681782,-19.387214,0.831347,0.000235,142.556443,65537,0,3200
3,39627322701121757,21.761322,-19.422856,0.558969,0.000084,41.997789,65537,0,3200
5,39627322701123650,21.817680,-19.392824,0.797495,0.000126,147.475980,65537,0,3200
8,39627322701125067,21.856479,-19.403721,0.798628,0.000072,76.810981,65537,0,3200
9,39627322701125474,21.867706,-19.384865,0.834056,0.000323,177.570769,65537,0,3200

In [6]:
output_path = './LRG_clean.fits'
cu.savefile(df_save, output_path)

# BGS

In [7]:
path = './BGS_ANY_full_noveto.dat.fits'
with fits.open(path) as hdul:
    header = hdul[1].header
    data = hdul[1].data
    tab = Table(data)

In [8]:
tab.columns

<TableColumns names=('TARGETID','MWS_TARGET','SUBPRIORITY','PRIORITY_INIT','TARGET_STATE','TIMESTAMP','LOCATION','TILEID','TILELOCID','LASTNIGHT','Z','ZERR','ZWARN','CHI2','COEFF','NPIXELS','SPECTYPE','SUBTYPE','NCOEFF','DELTACHI2','FIBER','COADD_FIBERSTATUS','FIBERASSIGN_X','FIBERASSIGN_Y','PRIORITY','COADD_NUMEXP','COADD_EXPTIME','COADD_NUMNIGHT','MEAN_DELTA_X','RMS_DELTA_X','MEAN_DELTA_Y','RMS_DELTA_Y','MEAN_PSF_TO_FIBER_SPECFLUX','TSNR2_ELG_B','TSNR2_LYA_B','TSNR2_BGS_B','TSNR2_QSO_B','TSNR2_LRG_B','TSNR2_ELG_R','TSNR2_LYA_R','TSNR2_BGS_R','TSNR2_QSO_R','TSNR2_LRG_R','TSNR2_ELG_Z','TSNR2_LYA_Z','TSNR2_BGS_Z','TSNR2_QSO_Z','TSNR2_LRG_Z','TSNR2_ELG','TSNR2_LYA','TSNR2_BGS','TSNR2_QSO','TSNR2_LRG','ZWARN_MTL','Z_QN','Z_QN_CONF','IS_QSO_QN','PRIORITY_ASSIGNED','GOODPRI','GOODHARDLOC','LOCATION_ASSIGNED','TILELOCID_ASSIGNED','NTILE','TILES','TILELOCIDS','BRICKID','BRICKNAME','MORPHTYPE','RA','DEC','DCHISQ','EBV','FLUX_G','FLUX_R','FLUX_Z','FLUX_IVAR_G','FLUX_IVAR_R','FLUX_IVAR_Z','MW_TRANSMISSION_G','MW_TRANSMISSION_R','MW_TRANSMISSION_Z','NOBS_G','NOBS_R','NOBS_Z','PSFDEPTH_G','PSFDEPTH_R','PSFDEPTH_Z','GALDEPTH_G','GALDEPTH_R','GALDEPTH_Z','FLUX_W1','FLUX_W2','FLUX_IVAR_W1','FLUX_IVAR_W2','MW_TRANSMISSION_W1','MW_TRANSMISSION_W2','FIBERFLUX_G','FIBERFLUX_R','FIBERFLUX_Z','FIBERTOTFLUX_G','FIBERTOTFLUX_R','FIBERTOTFLUX_Z','WISEMASK_W1','WISEMASK_W2','MASKBITS','SHAPE_R','PHOTSYS','DESI_TARGET','BGS_TARGET','COMP_TILE','FRACZ_TILELOCID','WEIGHT_ZFAIL','mod_success_rate')>

In [9]:
cols = ['TARGETID', 'RA', 'DEC', 'Z', 'ZERR', 'ZWARN',
        'SPECTYPE', 'DELTACHI2', 'MASKBITS', 'DESI_TARGET', 'BGS_TARGET',
        'PRIORITY', 'MORPHTYPE',
        'FLUX_G','FLUX_R','FLUX_Z', 'FLUX_W1','FLUX_W2',
        'FLUX_IVAR_G','FLUX_IVAR_R','FLUX_IVAR_Z','FLUX_IVAR_W1','FLUX_IVAR_W2']
df = tab[cols].to_pandas()

In [10]:
# clean
# ref: Zhou2024
mask = df['SPECTYPE'] == 'GALAXY'
mask &= df['ZWARN'] == 0
mask &= df['MASKBITS'] == 0
mask &= df['MORPHTYPE'] != 'PSF'
mask &= (df['DESI_TARGET'] & 2**60) != 0 # BGS
mask &= (df['FLUX_G']>0) & (df['FLUX_R']>0) & (df['FLUX_Z']>0) 
mask &= (df['FLUX_W1']>0) & (df['FLUX_W2']>0)
mask &= (df['FLUX_IVAR_G']>0) & (df['FLUX_IVAR_R']>0) & (df['FLUX_IVAR_Z']>0) 
mask &= (df['FLUX_IVAR_W1']>0) & (df['FLUX_IVAR_W2']>0)
mask &= df['DELTACHI2'] > 25

cols_save = ['TARGETID', 'RA', 'DEC', 'Z', 'ZERR',
            'DELTACHI2', 'DESI_TARGET', 'BGS_TARGET',
            'PRIORITY']

df_save = df[mask][cols_save]
print(df_save.shape)
df_save.head()

(5572969, 9)

,TARGETID,RA,DEC,Z,ZERR,DELTACHI2,DESI_TARGET,BGS_TARGET,PRIORITY
0,39627322533347488,11.120287,-19.383037,0.393356,0.000003,7702.837605,1152921504606846976,65537,2000
1,39627322533349236,11.169502,-19.386180,0.431841,0.000017,231.770113,1152921504606846976,65537,2000
2,39627322533350395,11.201714,-19.375325,0.274081,0.000071,319.995682,1152921504606846976,131074,2100
7,39627322696933171,21.663863,-19.388310,1.664652,0.000026,36.482376,1152921504606846976,65545,2100
12,39627322701120343,21.726569,-19.404268,0.034737,0.000003,1854.237051,1152921504606846976,131074,2100

In [11]:
output_path = './BGS_clean.fits'
cu.savefile(df_save, output_path)

# ELG

In [8]:
path = './ELG_LOPnotqso_full_noveto.dat.fits'
with fits.open(path) as hdul:
    header = hdul[1].header
    data = hdul[1].data
    tab = Table(data)

In [10]:
tab.columns

<TableColumns names=('TARGETID','MWS_TARGET','SUBPRIORITY','PRIORITY_INIT','TARGET_STATE','TIMESTAMP','LOCATION','TILEID','TILELOCID','LASTNIGHT','Z','ZERR','ZWARN','CHI2','COEFF','NPIXELS','SPECTYPE','SUBTYPE','NCOEFF','DELTACHI2','FIBER','COADD_FIBERSTATUS','FIBERASSIGN_X','FIBERASSIGN_Y','PRIORITY','COADD_NUMEXP','COADD_EXPTIME','COADD_NUMNIGHT','MEAN_DELTA_X','RMS_DELTA_X','MEAN_DELTA_Y','RMS_DELTA_Y','MEAN_PSF_TO_FIBER_SPECFLUX','TSNR2_ELG_B','TSNR2_LYA_B','TSNR2_BGS_B','TSNR2_QSO_B','TSNR2_LRG_B','TSNR2_ELG_R','TSNR2_LYA_R','TSNR2_BGS_R','TSNR2_QSO_R','TSNR2_LRG_R','TSNR2_ELG_Z','TSNR2_LYA_Z','TSNR2_BGS_Z','TSNR2_QSO_Z','TSNR2_LRG_Z','TSNR2_ELG','TSNR2_LYA','TSNR2_BGS','TSNR2_QSO','TSNR2_LRG','ZWARN_MTL','Z_QN','Z_QN_CONF','IS_QSO_QN','PRIORITY_ASSIGNED','GOODPRI','GOODHARDLOC','LOCATION_ASSIGNED','TILELOCID_ASSIGNED','NTILE','TILES','TILELOCIDS','BRICKID','BRICKNAME','MORPHTYPE','RA','DEC','DCHISQ','EBV','FLUX_G','FLUX_R','FLUX_Z','FLUX_IVAR_G','FLUX_IVAR_R','FLUX_IVAR_Z','MW_TRANSMISSION_G','MW_TRANSMISSION_R','MW_TRANSMISSION_Z','NOBS_G','NOBS_R','NOBS_Z','PSFDEPTH_G','PSFDEPTH_R','PSFDEPTH_Z','GALDEPTH_G','GALDEPTH_R','GALDEPTH_Z','FLUX_W1','FLUX_W2','FLUX_IVAR_W1','FLUX_IVAR_W2','MW_TRANSMISSION_W1','MW_TRANSMISSION_W2','FIBERFLUX_G','FIBERFLUX_R','FIBERFLUX_Z','FIBERTOTFLUX_G','FIBERTOTFLUX_R','FIBERTOTFLUX_Z','WISEMASK_W1','WISEMASK_W2','MASKBITS','SHAPE_R','PHOTSYS','DESI_TARGET','BGS_TARGET','OII_FLUX','OII_FLUX_IVAR','o2c','COMP_TILE','FRACZ_TILELOCID','WEIGHT_ZFAIL','mod_success_rate')>

In [12]:
cols = ['TARGETID', 'RA', 'DEC', 'Z', 'ZERR', 'ZWARN',
        'SPECTYPE', 'DELTACHI2', 'MASKBITS', 'DESI_TARGET', 'BGS_TARGET',
        'PRIORITY', 'MORPHTYPE',
        'FLUX_G','FLUX_R','FLUX_Z', 'FLUX_W1','FLUX_W2',
        'FLUX_IVAR_G','FLUX_IVAR_R','FLUX_IVAR_Z','FLUX_IVAR_W1','FLUX_IVAR_W2']
df = tab[cols].to_pandas()

In [16]:
df.head()

,TARGETID,RA,DEC,Z,ZERR,ZWARN,SPECTYPE,DELTACHI2,MASKBITS,DESI_TARGET,...,FLUX_G,FLUX_R,FLUX_Z,FLUX_W1,FLUX_W2,FLUX_IVAR_G,FLUX_IVAR_R,FLUX_IVAR_Z,FLUX_IVAR_W1,FLUX_IVAR_W2
0,39627322696934598,21.701752,-19.385530,NaN,NaN,999999,,NaN,0,655394,...,0.340674,0.363344,0.758265,0.702623,0.886887,3153.485840,1712.764893,174.354691,3.463370,0.710731
1,39627322701119858,21.713325,-19.406004,NaN,NaN,999999,,NaN,0,655394,...,0.326263,0.384721,0.682331,1.055155,0.920709,4408.660156,2862.971436,258.297058,3.497020,0.721873
2,39627322701120219,21.723061,-19.415860,NaN,NaN,999999,,NaN,0,655394,...,0.450910,0.667171,1.230853,0.945394,-2.340986,2323.593506,1429.400879,127.177528,3.345061,0.724299
3,39627322701120355,21.726791,-19.412397,NaN,NaN,999999,,NaN,0,655394,...,0.566380,0.741612,1.531818,1.184322,-0.925290,1987.373413,1216.564331,107.156387,3.294666,0.703301
4,39627322701120712,21.735261,-19.411350,1.086749,0.000031,0,GALAXY,159.182814,0,655394,...,0.868658,1.120541,2.142030,1.617592,2.827521,1688.823242,1035.519287,90.822998,3.208405,0.684590

In [18]:
# clean
# ref: Zhou2024
mask = df['SPECTYPE'] == 'GALAXY'
mask &= df['ZWARN'] == 0
mask &= df['MASKBITS'] == 0
mask &= df['MORPHTYPE'] != 'PSF'
mask &= (df['DESI_TARGET'] & 2**1) != 0 # ELG
mask &= (df['FLUX_G']>0) & (df['FLUX_R']>0) & (df['FLUX_Z']>0) 
mask &= (df['FLUX_W1']>0) & (df['FLUX_W2']>0)
mask &= (df['FLUX_IVAR_G']>0) & (df['FLUX_IVAR_R']>0) & (df['FLUX_IVAR_Z']>0) 
mask &= (df['FLUX_IVAR_W1']>0) & (df['FLUX_IVAR_W2']>0)
mask &= df['DELTACHI2'] > 25

cols_save = ['TARGETID', 'RA', 'DEC', 'Z', 'ZERR',
            'DELTACHI2', 'DESI_TARGET', 'BGS_TARGET',
            'PRIORITY']

df_save = df[mask][cols_save]
print(df_save.shape)
df_save.head()

(1214613, 9)

,TARGETID,RA,DEC,Z,ZERR,DELTACHI2,DESI_TARGET,BGS_TARGET,PRIORITY
4,39627322701120712,21.735261,-19.411350,1.086749,0.000031,159.182814,655394,0,3100
11,39627322701123110,21.800757,-19.410321,1.602472,0.000063,52.942696,655394,0,3100
100,39627328392796876,21.094503,-19.208232,1.012077,0.000026,1088.719380,655458,0,3200
209,39627328401184595,21.595608,-19.219013,0.971333,0.000043,78.724187,655394,0,3100
226,39627328401187179,21.670995,-19.348755,0.846038,0.000014,850.634299,655394,0,3100

In [19]:
output_path = './ELG_clean.fits'
cu.savefile(df_save, output_path)

# 合并LRG和BGS

In [12]:
bgs = cu.readfile('./BGS_clean.fits')
lrg = cu.readfile('./LRG_clean.fits')
elg = cu.readfile('./ELG_clean.fits')

In [13]:
# check duplicated
print(bgs.TARGETID.duplicated().sum())
print(lrg.TARGETID.duplicated().sum())
print(elg.TARGETID.duplicated().sum())

0
0
0

In [14]:
df_save = pd.concat([bgs, lrg, elg], axis=0)
df_save.columns = ['DESI_' + col for col in df_save.columns]

In [15]:
df_save.columns

Index(['DESI_TARGETID', 'DESI_RA', 'DESI_DEC', 'DESI_Z', 'DESI_ZERR',
       'DESI_DELTACHI2', 'DESI_DESI_TARGET', 'DESI_BGS_TARGET',
       'DESI_PRIORITY'],
      dtype='object')

In [17]:
output_path = 'desidr1.fits'
cu.savefile(df_save, output_path)